In [2]:
# libraries import
import pandas as pd
import numpy as np


# importing datasets
df_market  =     pd.read_csv("../datasets/estaticos_market.csv" , sep=',', encoding="utf8" )
df_portfolio1  = pd.read_csv("../datasets/estaticos_portfolio1.csv" , sep=',', encoding="utf8" )
df_portfolio2  = pd.read_csv("../datasets/estaticos_portfolio2.csv" , sep=',', encoding="utf8" )
df_portfolio3  = pd.read_csv("../datasets/estaticos_portfolio3.csv" , sep=',', encoding="utf8" )

In [3]:
df_market.columns.values

array(['Unnamed: 0', 'id', 'fl_matriz', 'de_natureza_juridica', 'sg_uf',
       'natureza_juridica_macro', 'de_ramo', 'setor',
       'idade_empresa_anos', 'idade_emp_cat', 'fl_me', 'fl_sa', 'fl_epp',
       'fl_mei', 'fl_ltda', 'dt_situacao', 'fl_st_especial', 'fl_email',
       'fl_telefone', 'fl_rm', 'nm_divisao', 'nm_segmento', 'fl_spa',
       'fl_antt', 'fl_veiculo', 'vl_total_tancagem',
       'vl_total_veiculos_antt', 'vl_total_veiculos_leves',
       'vl_total_veiculos_pesados', 'fl_optante_simples', 'qt_art',
       'vl_total_veiculos_pesados_grupo', 'vl_total_veiculos_leves_grupo',
       'vl_total_tancagem_grupo', 'vl_total_veiculos_antt_grupo',
       'vl_potenc_cons_oleo_gas', 'fl_optante_simei', 'sg_uf_matriz',
       'de_saude_tributaria', 'de_saude_rescencia', 'nu_meses_rescencia',
       'de_nivel_atividade', 'de_indicador_telefone',
       'fl_simples_irregular', 'vl_frota',
       'empsetorcensitariofaixarendapopulacao', 'nm_meso_regiao',
       'nm_micro_regiao', 'fl_passivel_iss', 'qt_socios', 'qt_socios_pf',
       'qt_socios_pj', 'idade_media_socios', 'idade_maxima_socios',
       'idade_minima_socios', 'qt_socios_st_regular',
       'qt_socios_st_suspensa', 'qt_socios_masculino',
       'qt_socios_feminino', 'qt_socios_pep', 'qt_alteracao_socio_total',
       'qt_alteracao_socio_90d', 'qt_alteracao_socio_180d',
       'qt_alteracao_socio_365d', 'qt_socios_pj_ativos',
       'qt_socios_pj_nulos', 'qt_socios_pj_baixados',
       'qt_socios_pj_suspensos', 'qt_socios_pj_inaptos',
       'vl_idade_media_socios_pj', 'vl_idade_maxima_socios_pj',
       'vl_idade_minima_socios_pj', 'qt_coligados', 'qt_socios_coligados',
       'qt_coligados_matriz', 'qt_coligados_ativo',
       'qt_coligados_baixada', 'qt_coligados_inapta',
       'qt_coligados_suspensa', 'qt_coligados_nula',
       'idade_media_coligadas', 'idade_maxima_coligadas',
       'idade_minima_coligadas', 'coligada_mais_nova_ativa',
       'coligada_mais_antiga_ativa', 'idade_media_coligadas_ativas',
       'coligada_mais_nova_baixada', 'coligada_mais_antiga_baixada',
       'idade_media_coligadas_baixadas', 'qt_coligados_sa',
       'qt_coligados_me', 'qt_coligados_mei', 'qt_coligados_ltda',
       'qt_coligados_epp', 'qt_coligados_norte', 'qt_coligados_sul',
       'qt_coligados_nordeste', 'qt_coligados_centro',
       'qt_coligados_sudeste', 'qt_coligados_exterior',
       'qt_ufs_coligados', 'qt_regioes_coligados', 'qt_ramos_coligados',
       'qt_coligados_industria', 'qt_coligados_agropecuaria',
       'qt_coligados_comercio', 'qt_coligados_servi√ßo',
       'qt_coligados_ccivil', 'qt_funcionarios_coligados',
       'qt_funcionarios_coligados_gp', 'media_funcionarios_coligados_gp',
       'max_funcionarios_coligados_gp', 'min_funcionarios_coligados_gp',
       'vl_folha_coligados', 'media_vl_folha_coligados',
       'max_vl_folha_coligados', 'min_vl_folha_coligados',
       'vl_folha_coligados_gp', 'media_vl_folha_coligados_gp',
       'max_vl_folha_coligados_gp', 'min_vl_folha_coligados_gp',
       'faturamento_est_coligados', 'media_faturamento_est_coligados',
       'max_faturamento_est_coligados', 'min_faturamento_est_coligados',
       'faturamento_est_coligados_gp',
       'media_faturamento_est_coligados_gp',
       'max_faturamento_est_coligados_gp',
       'min_faturamento_est_coligados_gp', 'total_filiais_coligados',
       'media_filiais_coligados', 'max_filiais_coligados',
       'min_filiais_coligados', 'qt_coligados_atividade_alto',
       'qt_coligados_atividade_medio', 'qt_coligados_atividade_baixo',
       'qt_coligados_atividade_mt_baixo',
       'qt_coligados_atividade_inativo', 'qt_coligadas',
       'sum_faturamento_estimado_coligadas',
       'de_faixa_faturamento_estimado',
       'de_faixa_faturamento_estimado_grupo',
       'vl_faturamento_estimado_aux', 'vl_faturamento_estimado_grupo_aux',
       'qt_ex_funcionarios', 'qt_funcionarios_grupo',
       'percent_func_genero_masc', 'percent_func_genero_fem',
       'idade_ate_18', 'idade_de_19_a_23', 'idade_de_24_a_28',
       'idade_de_29_a_33', 'idade_de_34_a_38', 'idade_de_39_a_43',
       'idade_de_44_a_48', 'idade_de_49_a_53', 'idade_de_54_a_58',
       'idade_acima_de_58', 'grau_instrucao_macro_analfabeto',
       'grau_instrucao_macro_escolaridade_fundamental',
       'grau_instrucao_macro_escolaridade_media',
       'grau_instrucao_macro_escolaridade_superior',
       'grau_instrucao_macro_desconhecido', 'total',
       'meses_ultima_contratacaco', 'qt_admitidos_12meses',
       'qt_desligados_12meses', 'qt_desligados', 'qt_admitidos',
       'media_meses_servicos_all', 'max_meses_servicos_all',
       'min_meses_servicos_all', 'media_meses_servicos',
       'max_meses_servicos', 'min_meses_servicos', 'qt_funcionarios',
       'qt_funcionarios_12meses', 'qt_funcionarios_24meses',
       'tx_crescimento_12meses', 'tx_crescimento_24meses',
       'tx_rotatividade', 'qt_filiais'], dtype=object)

In [10]:
# code from rocketchat @matheus 
def get_metadata(df, features=None):
    df = df.copy()
    if features is None:
        features = list(df.columns)
        
    total_missing = df[features].isnull().sum()
    percent_missing = (df[features].isnull().sum()/df[features].isnull().count()).round(3)
    distinct_values = df.nunique(dropna=False)
    types = df.dtypes
    meta_data = pd.concat([total_missing, percent_missing, distinct_values, types],
                          axis=1, keys=['Total Missing', 'Percent Missing', 'Distinct Values', 'Type'])
    return meta_data.sort_values('Percent Missing', ascending=False)

market_data = get_metadata(df_market)

In [13]:
market_data

,Total Missing,Percent Missing,Distinct Values,Type
qt_alteracao_socio_90d,462298,1.000,1,float64
idade_media_coligadas_baixadas,462162,1.000,49,float64
qt_alteracao_socio_total,462298,1.000,1,float64
coligada_mais_antiga_baixada,462162,1.000,47,float64
coligada_mais_nova_baixada,462162,1.000,47,float64
vl_total_veiculos_antt,462122,1.000,21,float64
grau_instrucao_macro_desconhecido,462298,1.000,1,float64
qt_alteracao_socio_180d,462298,1.000,1,float64
qt_alteracao_socio_365d,462298,1.000,1,float64
vl_total_veiculos_antt_grupo,461962,0.999,32,float64
vl_total_tancagem,462018,0.999,34,float64
grau_instrucao_macro_analfabeto,460414,0.996,35,float64
vl_total_tancagem_grupo,460538,0.996,107,float64
idade_ate_18,459392,0.994,34,float64
qt_socios_st_suspensa,459047,0.993,5,float64
vl_potenc_cons_oleo_gas,458615,0.992,156,float64
vl_idade_maxima_socios_pj,457754,0.990,1945,float64
qt_socios_pj_inaptos,457754,0.990,6,float64
vl_idade_minima_socios_pj,457754,0.990,1953,float64
vl_idade_media_socios_pj,457754,0.990,2193,float64
qt_socios_pj_baixados,457754,0.990,4,float64
qt_socios_pj_ativos,457754,0.990,12,float64
qt_socios_pj_nulos,457754,0.990,3,float64
qt_socios_pj_suspensos,457754,0.990,4,float64
qt_art,455708,0.986,121,float64
qt_socios_pep,455555,0.985,32,float64
idade_acima_de_58,451272,0.976,177,float64
idade_de_54_a_58,448323,0.970,165,float64
idade_de_49_a_53,443261,0.959,192,float64
media_filiais_coligados,441898,0.956,756,float64
...,...,...,...,...
Unnamed: 0,0,0.000,462298,int64
id,0,0.000,462298,object
dt_situacao,6,0.000,7335,object
fl_matriz,0,0.000,2,int8
de_natureza_juridica,0,0.000,67,object
sg_uf,0,0.000,6,int8
natureza_juridica_macro,0,0.000,7,object
de_ramo,0,0.000,33,object
idade_empresa_anos,0,0.000,14198,float64
idade_emp_cat,0,0.000,6,int8
fl_me,0,0.000,2,int8
fl_sa,0,0.000,2,int8
fl_epp,0,0.000,1,int8
fl_mei,0,0.000,2,int8
fl_ltda,0,0.000,2,int8
fl_st_especial,0,0.000,2,int8
fl_passivel_iss,0,0.000,3,int8
fl_email,0,0.000,2,int8
fl_telefone,0,0.000,2,int8
fl_rm,0,0.000,2,int8
fl_spa,0,0.000,3,int8
fl_antt,0,0.000,3,int8
fl_veiculo,0,0.000,3,int8
fl_optante_simples,0,0.000,3,int8
fl_optante_simei,0,0.000,3,int8
sg_uf_matriz,0,0.000,28,int8
de_saude_tributaria,0,0.000,7,int8
de_saude_rescencia,0,0.000,6,int8
fl_simples_irregular,0,0.000,3,int8
qt_filiais,0,0.000,304,int64

In [15]:
# code from rocketchat @matheus 
def get_metadata(df, features=None):
    df = df.copy()
    if features is None:
        features = list(df.columns)
        
    total_missing = df[features].isnull().sum()
    percent_missing = (df[features].isnull().sum()/df[features].isnull().count()).round(3)
    distinct_values = df.nunique(dropna=False)
    types = df.dtypes
    meta_data = pd.concat([total_missing, percent_missing, distinct_values, types],
                          axis=1, keys=['Total Missing', 'Percent Missing', 'Distinct Values', 'Type'])
    return meta_data.sort_values('Percent Missing', ascending=False)

portfolio1_data = get_metadata(df_portfolio1)
portfolio1_data

,Total Missing,Percent Missing,Distinct Values,Type
qt_alteracao_socio_total,555,1.000,1,float64
qt_alteracao_socio_365d,555,1.000,1,float64
vl_total_veiculos_antt_grupo,555,1.000,1,float64
vl_total_tancagem_grupo,555,1.000,1,float64
idade_media_coligadas_baixadas,555,1.000,1,float64
coligada_mais_antiga_baixada,555,1.000,1,float64
coligada_mais_nova_baixada,555,1.000,1,float64
qt_alteracao_socio_90d,555,1.000,1,float64
vl_total_veiculos_antt,555,1.000,1,float64
vl_total_tancagem,555,1.000,1,float64
qt_alteracao_socio_180d,555,1.000,1,float64
grau_instrucao_macro_desconhecido,555,1.000,1,float64
grau_instrucao_macro_analfabeto,554,0.998,2,float64
vl_idade_media_socios_pj,553,0.996,3,float64
qt_socios_pj_inaptos,553,0.996,2,float64
vl_idade_minima_socios_pj,553,0.996,3,float64
vl_idade_maxima_socios_pj,553,0.996,3,float64
qt_socios_pj_ativos,553,0.996,3,float64
qt_socios_pj_nulos,553,0.996,2,float64
qt_socios_pj_baixados,553,0.996,2,float64
qt_socios_pj_suspensos,553,0.996,2,float64
vl_potenc_cons_oleo_gas,552,0.995,4,float64
idade_ate_18,551,0.993,2,float64
qt_socios_pep,551,0.993,3,float64
qt_art,551,0.993,4,float64
qt_socios_st_suspensa,548,0.987,2,float64
idade_de_54_a_58,541,0.975,3,float64
media_filiais_coligados,540,0.973,11,float64
min_filiais_coligados,540,0.973,9,float64
total_filiais_coligados,540,0.973,12,float64
...,...,...,...,...
id,0,0.000,555,object
fl_passivel_iss,0,0.000,2,bool
fl_matriz,0,0.000,2,bool
de_natureza_juridica,0,0.000,6,object
sg_uf,0,0.000,6,object
natureza_juridica_macro,0,0.000,2,object
de_ramo,0,0.000,2,object
setor,0,0.000,3,object
idade_empresa_anos,0,0.000,522,float64
idade_emp_cat,0,0.000,6,object
fl_me,0,0.000,2,bool
fl_sa,0,0.000,2,bool
fl_epp,0,0.000,1,bool
fl_mei,0,0.000,2,bool
fl_ltda,0,0.000,1,bool
dt_situacao,0,0.000,416,object
fl_st_especial,0,0.000,1,bool
fl_email,0,0.000,2,bool
fl_telefone,0,0.000,2,bool
fl_rm,0,0.000,2,object
nm_divisao,0,0.000,8,object
nm_segmento,0,0.000,2,object
fl_spa,0,0.000,1,bool
fl_antt,0,0.000,2,bool
fl_veiculo,0,0.000,2,bool
vl_total_veiculos_pesados_grupo,0,0.000,9,int64
vl_total_veiculos_leves_grupo,0,0.000,10,int64
sg_uf_matriz,0,0.000,7,object
fl_simples_irregular,0,0.000,1,bool
qt_filiais,0,0.000,15,int64

In [16]:
# code from rocketchat @matheus 
def get_metadata(df, features=None):
    df = df.copy()
    if features is None:
        features = list(df.columns)
        
    total_missing = df[features].isnull().sum()
    percent_missing = (df[features].isnull().sum()/df[features].isnull().count()).round(3)
    distinct_values = df.nunique(dropna=False)
    types = df.dtypes
    meta_data = pd.concat([total_missing, percent_missing, distinct_values, types],
                          axis=1, keys=['Total Missing', 'Percent Missing', 'Distinct Values', 'Type'])
    return meta_data.sort_values('Percent Missing', ascending=False)

portfolio2_data = get_metadata(df_portfolio2)
portfolio2_data

            Total Missing  Percent Missing  Distinct Values    Type
Unnamed: 0              0              0.0              566   int64
id                      0              0.0              566  object

In [18]:
# code from rocketchat @matheus 
def get_metadata(df, features=None):
    df = df.copy()
    if features is None:
        features = list(df.columns)
        
    total_missing = df[features].isnull().sum()
    percent_missing = (df[features].isnull().sum()/df[features].isnull().count()).round(3)
    distinct_values = df.nunique(dropna=False)
    types = df.dtypes
    meta_data = pd.concat([total_missing, percent_missing, distinct_values, types],
                          axis=1, keys=['Total Missing', 'Percent Missing', 'Distinct Values', 'Type'])
    return meta_data.sort_values('Percent Missing', ascending=False)

portfolio3_data = get_metadata(df_portfolio3)
portfolio3_data

            Total Missing  Percent Missing  Distinct Values    Type
Unnamed: 0              0              0.0              265   int64
id                      0              0.0              265  object

## Data cleaning - Market

In [5]:
# Ajusting some features from market
features = [
            'fl_matriz',
            'fl_me',
            'fl_sa',
            'fl_epp',
            'fl_mei',
            'fl_ltda',
            'fl_st_especial',
            'fl_email',
            'fl_telefone',
            'fl_rm',
            'fl_optante_simples',
            'fl_optante_simei',
            'fl_optante_simples',
            'fl_optante_simei',
            'fl_simples_irregular',    
            'fl_passivel_iss',
            'fl_spa',
            'fl_antt',
            'fl_veiculo',
            'sg_uf',
            'idade_emp_cat',
            'sg_uf_matriz',
            'de_saude_tributaria',
            'de_saude_rescencia'
           ]

In [6]:

# Show features with count by nulls values

list1= []
for x in df_market[features]:
    list1.append( {'Features': df_market[x].name, 'Nulls': df_market[x].isnull().sum()} )

view = pd.DataFrame(list1).sort_values('Nulls', ascending=False)
view

                Features  Nulls
12    fl_optante_simples  82713
10    fl_optante_simples  82713
13      fl_optante_simei  82713
11      fl_optante_simei  82713
22   de_saude_tributaria  14851
23    de_saude_rescencia  14851
21          sg_uf_matriz   1939
15       fl_passivel_iss   1927
16                fl_spa   1927
18            fl_veiculo   1927
17               fl_antt   1927
14  fl_simples_irregular   1927
2                  fl_sa      0
20         idade_emp_cat      0
19                 sg_uf      0
6         fl_st_especial      0
7               fl_email      0
3                 fl_epp      0
1                  fl_me      0
4                 fl_mei      0
5                fl_ltda      0
9                  fl_rm      0
8            fl_telefone      0
0              fl_matriz      0

In [7]:
# change columns True and False to binary
df_market['fl_matriz'] =     df_market['fl_matriz'].astype("category").cat.codes
df_market['fl_me']=          df_market['fl_me'].astype("category").cat.codes
df_market['fl_sa']=          df_market['fl_sa'].astype("category").cat.codes
df_market['fl_epp']=         df_market['fl_epp'].astype("category").cat.codes
df_market['fl_mei'] =        df_market['fl_mei'].astype("category").cat.codes
df_market['fl_ltda']=        df_market['fl_ltda'].astype("category").cat.codes
df_market['fl_st_especial']= df_market['fl_st_especial'].astype("category").cat.codes
df_market['fl_email']=       df_market['fl_email'].astype("category").cat.codes
df_market['fl_telefone'] =   df_market['fl_telefone'].astype("category").cat.codes
df_market['fl_rm'] =                df_market['fl_rm'].astype("category").cat.codes
df_market['fl_optante_simples'] =   df_market['fl_optante_simples'].astype("category").cat.codes
df_market['fl_optante_simei'] =     df_market['fl_optante_simei'].astype("category").cat.codes
df_market['fl_optante_simples'] =   df_market['fl_optante_simples'].astype("category").cat.codes
df_market['fl_optante_simei'] =     df_market['fl_optante_simei'].astype("category").cat.codes
df_market['fl_simples_irregular'] = df_market['fl_simples_irregular'].astype("category").cat.codes
df_market['fl_passivel_iss'] =      df_market['fl_passivel_iss'].astype("category").cat.codes
df_market['fl_spa'] =               df_market['fl_spa'].astype("category").cat.codes
df_market['fl_antt'] =              df_market['fl_antt'].astype("category").cat.codes
df_market['fl_veiculo'] =           df_market['fl_veiculo'].astype("category").cat.codes


# change columns to binary
df_market['sg_uf'] =               df_market['sg_uf'].astype("category").cat.codes
df_market['idade_emp_cat'] =       df_market['idade_emp_cat'].astype("category").cat.codes
df_market['sg_uf_matriz'] =        df_market['sg_uf_matriz'].astype("category").cat.codes
df_market['de_saude_tributaria'] = df_market['de_saude_tributaria'].astype("category").cat.codes 
df_market['de_saude_rescencia'] =  df_market['de_saude_rescencia'].astype("category").cat.codes

In [8]:

df_market[df_market.columns[170:200]]

df_market['de_nivel_atividade'].unique()

array(['ALTA', 'BAIXA', 'MEDIA', nan, 'MUITO BAIXA'], dtype=object)

In [9]:
df_market

,Unnamed: 0,id,fl_matriz,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,setor,idade_empresa_anos,idade_emp_cat,...,media_meses_servicos,max_meses_servicos,min_meses_servicos,qt_funcionarios,qt_funcionarios_12meses,qt_funcionarios_24meses,tx_crescimento_12meses,tx_crescimento_24meses,tx_rotatividade,qt_filiais
0,0,a6984c3ae395090e3bee8ad63c3758b110de096d5d8195...,1,SOCIEDADE EMPRESARIA LIMITADA,4,ENTIDADES EMPRESARIAIS,INDUSTRIA DA CONSTRUCAO,CONSTRU√á√ÉO CIVIL,14.457534,1,...,43.738462,93.266667,19.166667,26.0,26.0,27.0,0.000000,-3.703704,0.000000,0
1,1,6178f41ade1365e44bc2c46654c2c8c0eaae27dcb476c4...,1,EMPRESARIO INDIVIDUAL,3,OUTROS,SERVICOS DE ALOJAMENTO/ALIMENTACAO,SERVI√áO,1.463014,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2,4a7e5069a397f12fdd7fd57111d6dc5d3ba558958efc02...,1,EMPRESARIO INDIVIDUAL,1,OUTROS,"TRANSPORTE, ARMAZENAGEM E CORREIO",SERVI√áO,7.093151,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,3,3348900fe63216a439d2e5238c79ddd46ede454df7b9d8...,1,EMPRESARIO INDIVIDUAL,1,OUTROS,SERVICOS DIVERSOS,SERVI√áO,6.512329,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,4,1f9bcabc9d3173c1fe769899e4fac14b053037b953a1e4...,1,EMPRESARIO INDIVIDUAL,4,OUTROS,"SERVICOS PROFISSIONAIS, TECNICOS E CIENTIFICOS",SERVI√áO,3.200000,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5,5,529a1f5fc6f88071db7d38492a0ce7c985c77e9b1c3bb6...,1,SOCIEDADE EMPRESARIA LIMITADA,4,ENTIDADES EMPRESARIAIS,QUIMICA-PETROQUIMICA,INDUSTRIA,38.079452,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
6,6,8bf37c178778e537b108e58bf20552abe10c3a7fae129b...,1,EMPRESARIO INDIVIDUAL,2,OUTROS,"TRANSPORTE, ARMAZENAGEM E CORREIO",SERVI√áO,7.276712,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
7,7,0114fd3fbdc347c561843cde6aece12e8e53cb5d32c77d...,1,EMPRESARIO INDIVIDUAL,4,OUTROS,SERVICOS ADMINISTRATIVOS,SERVI√áO,0.052055,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
8,8,6c45aabb849a760a3a7107c7a61262642f683feb8912a4...,1,COOPERATIVA,1,ENTIDADES EMPRESARIAIS,BENS DE CONSUMO,INDUSTRIA,12.263014,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
9,9,2fcd678d71b04ccb77644fff57706bdc7fcfbbec6b1926...,0,EMPRESARIO INDIVIDUAL,4,OUTROS,COMERCIO VAREJISTA,COMERCIO,17.942466,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
10,10,5e88eba292754550f48fb752318a0ebbbf8c46e8480531...,1,EMPRESARIO INDIVIDUAL,4,OUTROS,COMERCIO VAREJISTA,COMERCIO,7.764384,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
11,11,3d7a24d9830055fd8aeaec2fcc8ef5b248d8b0d6f780b5...,1,EMPRESARIO INDIVIDUAL,5,OUTROS,COMERCIO VAREJISTA,COMERCIO,6.775342,3,...,38.781818,70.833333,5.966667,11.0,10.0,8.0,10.000000,37.500000,0.000000,0
12,12,ae7aa54603064698a34a870f9e06364ae63466b55e914d...,1,EMPRESARIO INDIVIDUAL,3,OUTROS,SERVICOS ADMINISTRATIVOS,SERVI√áO,12.838356,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
13,13,1e954ad5e6a5b7af8582da953709cd702a2f5e5d674361...,1,EMPRESARIO INDIVIDUAL,1,OUTROS,SERVICOS DE ALOJAMENTO/ALIMENTACAO,SERVI√áO,3.690411,0,...,26.233333,26.233333,26.233333,2.0,2.0,2.0,0.000000,0.000000,0.000000,0
14,14,b0ab88c6ae5e0846f0b8bd63b8472e9ecb73edf9188ff1...,1,EMPRESARIO INDIVIDUAL,4,OUTROS,INDUSTRIA DA CONSTRUCAO,CONSTRU√á√ÉO CIVIL,2.564384,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
15,15,8d3c6909ab111449f2db1937961f55046f21a86147c0f3...,1,ASSOCIACAO PRIVADA,5,ENTIDADES SEM FINS LUCRATIVOS,SERVICOS DIVERSOS,SERVI√áO,21.241096,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
16,16,c30c81b4e8526ce3cfe4dda880795e1c4353d39058ddad...,1,ASSOCIACAO PRIVADA,3,ENTIDADES SEM FINS LUCRATIVOS,SERVICOS DIVERSOS,SERVI√áO,30.873973,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
17,17,82aa41448d40afef92908fdfaa7070b2eedb2ffacb1016...,1,EMPRESARIO INDIVIDUAL,5,OUTROS,INDUSTRIA DA CONSTRUCAO,CONSTRU√á√ÉO CIVIL,3.986301,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
18,18,9907170763d88708043f32bc265fbf544d69f966052920...,1,EMPRESARIO INDIVIDUAL,2,OUTROS,BENS DE CONSUMO,SERVI√áO,3.583562,0,...,25.750000,34.366667,17.133333,2.0,2.0,1.0,0.000000,100.000000,0.000000,0
19,19,3d280e33e53e6fa5d63791f1eaf0207f2c079d1d713175...,1,EMPRESARIO INDIVIDUAL,3,OUTROS,COMERCIO VAREJISTA,COMERCIO,6.323288,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
20,20,b047290aec7450aa81dda8aff9cb2e0bf4f01d15a43088...,1,EMPRESARIO INDIVIDUAL,5,OUTROS,INDUSTRIA DIGITAL,SERVI√áO,6.745205,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
21,21,459303e2f53eafe5c018c516d21f1cad65ab8a82c7214e...,1,EMPRESARIO INDIVIDUAL,1,OUTROS,COMERCIO VAREJISTA,COMERCIO,9.545205,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
22,22,4e663ebb51860ea4882099302347f35f3f255e184c3849...,1,EMPRESARIO INDIVIDUAL,3,OUTROS,COMERCIO VAREJISTA,COMERCIO,5.221918,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23,23,efdae0635be4d9b35bfa6292615edc7c103a22317e788a...,1,EMPRESARIO INDIVIDUAL,3,OUTROS,COMERCIO VAREJISTA,COMERCIO,2.624658,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
24,24,91e260a5a74fc61f90280da08eb356e4d74f913eac7780...,1,EMPRESARIO INDIVIDUAL,4,OUTROS,SERVICOS DIVERSOS,SERVI√áO,3.506849,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
25,25,e1df78e89a20f97ff7eace62578dc337c047ea604fc5f1...,1,SOCIEDADE EMPRESARIA LIMITADA,4,ENTIDADES EMPRESARIAIS,SERVICOS ADMINISTRATIVOS,SERVI√áO,9.230137,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
26,26,7da38db626e52ddea4e9a559fb7980567e2496ffcf8f12...,1,EMPRESARIO INDIVIDUAL,4,OUTROS,COMERCIO VAREJISTA,COMERCIO,9.980822,3,...,31.783333,82.033333,6.966667,8.0,9.0,6.0,-11.111111,33.333333,23.529412,0
27,27,0032e3e6a776cbf4d36efa963b4eda224ddba8af284117...,1,EMPRESARIO INDIVIDUAL,2,OUTROS,COMERCIO VAREJISTA,COMERCIO,6.090411,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
28,28,82d50cb9a323eb65714a527b594857abbabf5921279409...,1,EMPRESARIO INDIVIDUAL,5,OUTROS,SERVICOS DIVERSOS,SERVI√áO,29.443836,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
29,29,ba411f39a37e192eeec2c4d8a801702adcc5fa0f4f83af...,1,ASSOCIACAO PRIVADA,2,ENTIDADES SEM FINS LUCRATIVOS,SERVICOS DIVERSOS,SERVI√áO,7.016438,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462268,462268,b81118a8c6eb12e3c68a883f88642e7810b53e6d610c8e...,1,EMPRESARIO INDIVIDUAL,2,OUTROS,BENS DE CONSUMO,INDUSTRIA,8.454795,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462269,462269,c1ba53a06184825380c31d161b07a57dbdef8d9e3aae8a...,1,SOCIEDADE EMPRESARIA LIMITADA,3,ENTIDADES EMPRESARIAIS,INDUSTRIA DA CONSTRUCAO,CONSTRU√á√ÉO CIVIL,6.909589,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462270,462270,588847cbb782408a1fa8be46925d06903482acf455fa34...,1,EMPRESARIO INDIVIDUAL,4,OUTROS,BENS DE CONSUMO,INDUSTRIA,8.441096,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462271,462271,14a3cf18d01d2098e468510f2d24e1030bb52251a6e991...,1,EMPRESARIO INDIVIDUAL,4,OUTROS,COMERCIO VAREJISTA,COMERCIO,6.471233,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462272,462272,ba57e8f8416d1ca3cb2bd92e7e69c5bd6eb2807770ae0d...,1,EMPRESARIO INDIVIDUAL,2,OUTROS,COMERCIO VAREJISTA,COMERCIO,23.567123,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462273,462273,ecec017267fa83e13885e98c609de056c1d245d663cc91...,1,EMPRESARIO INDIVIDUAL,1,OUTROS,SERVICOS DIVERSOS,SERVI√áO,7.980822,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462274,462274,6d97cd42b5dd216ebf52c0d4d5043c132db326dc31ced1...,1,EMPRESARIO INDIVIDUAL,0,OUTROS,COMERCIO VAREJISTA,COMERCIO,0.032877,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462275,462275,82e06334d5572f40241451c4c5c28da54439846b80ddf6...,1,ASSOCIACAO PRIVADA,3,ENTIDADES SEM FINS LUCRATIVOS,SERVICOS DIVERSOS,SERVI√áO,21.482192,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462276,462276,a61242c63a1734a962c9a2d75b66aae659c4b2262c6e67...,1,SOCIEDADE EMPRESARIA LIMITADA,2,ENTIDADES EMPRESARIAIS,COMERCIO VAREJISTA,COMERCIO,14.219178,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462277,462277,b508a8f57e8d2f86d326b39b18397539ce9fce2121636b...,1,EMPRESARIO INDIVIDUAL,2,OUTROS,SERVICOS DE ALOJAMENTO/ALIMENTACAO,SERVI√áO,6.786301,3,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.000000,0
462278,462278,51acf389f5dc64726ae2523109df9dbf0b337dbf1a757b...,1,SOCIEDADE EMPRESARIA LIMITADA,3,ENTIDADES EMPRESARIAIS,INDUSTRIA DA CONSTRUCAO,CONSTRU√á√ÉO CIVIL,25.997260,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462279,462279,e32c194d3a1639d6f2f9c34c86d84a098a879a6fff74bd...,1,SOCIEDADE EMPRESARIA LIMITADA,3,ENTIDADES EMPRESARIAIS,INDUSTRIA DA CONSTRUCAO,CONSTRU√á√ÉO CIVIL,24.063014,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462280,462280,51395fd3eee3277a8cabefdfbd22dd079862ec1f491151...,1,ASSOCIACAO PRIVADA,2,ENTIDADES SEM FINS LUCRATIVOS,SERVICOS DIVERSOS,SERVI√áO,17.463014,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462281,462281,5d8a8ef6c379dad93e2b719f9a852b52adda2bf1a0a55b...,1,EMPRESARIO INDIVIDUAL,1,OUTROS,COMERCIO VAREJISTA,COMERCIO,5.923288,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462282,462282,5e03ec1a510c0168eb98b81da2b0d12d5e85e1e5c6639a...,1,EMPRESARIO INDIVIDUAL,3,OUTROS,INDUSTRIA DIGITAL,SERVI√áO,1.975342,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462283,462283,12f4ec7f51b860e99c645d2415a19e3f6e0a353b46db82...,1,ORGANIZACAO RELIGIOSA,4,ENTIDADES SEM FINS LUCRATIVOS,SERVICOS DIVERSOS,SERVI√áO,4.098630,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462284,462284,c4e15080db8edd47b56420271c7e3741d23d62bd964c09...,1,ORGANIZACAO RELIGIOSA,3,ENTIDADES SEM FINS LUCRATIVOS,SERVICOS DIVERSOS,SERVI√áO,6.200000,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462285,462285,c7d29b8f06b400d2664e93327d7c3379e25b0b04045e65...,1,EMPRESARIO INDIVIDUAL,3,OUTROS,SERVICOS DE ALOJAMENTO/ALIMENTACAO,SERVI√áO,1.180822,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462286,462286,0024d85b556fb57af505f67dcb02055fc25bd403f4f3af...,1,SOCIEDADE EMPRESARIA LIMITADA,1,ENTIDADES EMPRESARIAIS,COMERCIO POR ATACADO,COMERCIO,19.547945,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462287,462287,a875c3f73f2a18cb3f16aa3000ef7aaff1ec562bdfbe46...,1,EMPRESARIO INDIVIDUAL,0,OUTROS,SERVICOS DIVERSOS,SERVI√áO,7.778082,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462288,462288,25fc6c2f86ea82180b19935893969ca5943af053cf4fa6...,1,EMPRESARIO INDIVIDUAL,1,OUTROS,COMERCIO VAREJISTA,COMERCIO,14.586301,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462289,462289,7217389b17042e97dd2b35899f375aabd40901c90f26b4...,1,EMPRESARIO INDIVIDUAL,5,OUTROS,TEXTEIS,INDUSTRIA,0.687671,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462290,462290,6d1d4e188e3314878b59649c4f840e0ca141a3c03d5bfc...,1,SOCIEDADE EMPRESARIA LIMITADA,2,ENTIDADES EMPRESARIAIS,SERVICOS ADMINISTRATIVOS,SERVI√áO,9.238356,3,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.000000,0
462291,462291,916d935f687e32f7c3efb21e982d908074d74eecf7ef4a...,1,EMPRESARIO INDIVIDUAL,3,OUTROS,SERVICOS DIVERSOS,SERVI√áO,12.728767,1,...,129.766667,129.766667,129.766667,1.0,1.0,1.0,0.000000,0.000000,0.000000,0
462292,462292,a29ac8a2e3a0bd8b806a7d62d135c806de7004dc088485...,1,ENTIDADE SINDICAL,5,ENTIDADES SEM FINS LUCRATIVOS,SERVICOS DIVERSOS,SERVI√áO,16.849315,2,...,NaN,NaN,NaN,0.0,0.0,1.0,NaN,-100.000000,0.000000,0
462293,462293,469ee5fc984d0bb60aa2f40cda4d003d7c9b963d149ed3...,1,EMPRESARIO INDIVIDUAL,4,OUTROS,COMERCIO E REPARACAO DE VEICULOS,COMERCIO,3.254795,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462294,462294,656f496e7e2fad708f0022d8ad97d2cb9344e839a5f3cb...,1,EMPRESARIO INDIVIDUAL,3,OUTROS,SERVICOS ADMINISTRATIVOS,SERVI√áO,8.953425,3,...,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.000000,0
462295,462295,9b933a5cf2149d1338f00fb459d34a16b9b0f2e8d3e8e1...,1,ASSOCIACAO PRIVADA,2,ENTIDADES SEM FINS LUCRATIVOS,SERVICOS DE SAUDE,SERVI√áO,20.745205,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
462296,462296,84db0f17467cf4f02439e01ade57150b6ac59d9dae53ed...,1,SOCIEDADE EMPRESARIA LIMITADA,5,ENTIDADES EMPRESARIAIS,COMERCIO VAREJISTA,COMERCIO,1.909589,0,...,13.422222,19.733333,2.400000,3.0,2.0,0.0,50.000000,NaN,0.000000,0
462297,462297,3d43e934e150b86be1e67524f5ba1018b27da9ef25566d...,1,EMPRESARIO INDIVIDUAL,5,OUTROS,"TRANSPORTE, ARMAZENAGEM E CORREIO",SERVI√áO,0.797260,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0